// Autogenerated by png_to_header.py v0.2.0
// Do not edit manually!

#include "img_blank.h"
#include "img_disttest.h"
#include "img_dual.h"
#include "img_linrainbow.h"
#include "img_maze.h"
#include "img_rgbm.h"
#include "img_single.h"
#include "img_square8.h"
#include "img_zigzag.h"