// Autogenerated by png_to_header.py v0.2.0
// Do not edit manually!

#include "gol_glider1.h"
#include "gol_glider2.h"
#include "gol_o112p15.h"
#include "gol_p144.h"
#include "gol_pulsar.h"
#include "gol_rpentomino.h"
#include "gol_ships.h"